name: work
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_native_splash: ^2.4.6
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/


flutter_native_splash:
  color: "#ffffff" # background color
  image: assets/images/logo.png # your logo
  android: true
  ios: true

